/*
 * Copyright 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.devwindsw.lifeonearth.feature.unsplash.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.devwindsw.lifeonearth.feature.unsplash.icons.UnsplashIcons

// Source from https://fonts.google.com/icons
// Generated by "Svg to Compose" of Pavel Shurmilov
public val UnsplashIcons.Download24px: ImageVector
    get() {
        if (_download24px != null) {
            return _download24px!!
        }
        _download24px = Builder(name = "Download24px", defaultWidth = 24.0.dp, defaultHeight =
                24.0.dp, viewportWidth = 960.0f, viewportHeight = 960.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(480.0f, 640.0f)
                lineTo(280.0f, 440.0f)
                lineTo(336.0f, 382.0f)
                lineTo(440.0f, 486.0f)
                lineTo(440.0f, 160.0f)
                lineTo(520.0f, 160.0f)
                lineTo(520.0f, 486.0f)
                lineTo(624.0f, 382.0f)
                lineTo(680.0f, 440.0f)
                lineTo(480.0f, 640.0f)
                close()
                moveTo(240.0f, 800.0f)
                quadTo(207.0f, 800.0f, 183.5f, 776.5f)
                quadTo(160.0f, 753.0f, 160.0f, 720.0f)
                lineTo(160.0f, 600.0f)
                lineTo(240.0f, 600.0f)
                lineTo(240.0f, 720.0f)
                quadTo(240.0f, 720.0f, 240.0f, 720.0f)
                quadTo(240.0f, 720.0f, 240.0f, 720.0f)
                lineTo(720.0f, 720.0f)
                quadTo(720.0f, 720.0f, 720.0f, 720.0f)
                quadTo(720.0f, 720.0f, 720.0f, 720.0f)
                lineTo(720.0f, 600.0f)
                lineTo(800.0f, 600.0f)
                lineTo(800.0f, 720.0f)
                quadTo(800.0f, 753.0f, 776.5f, 776.5f)
                quadTo(753.0f, 800.0f, 720.0f, 800.0f)
                lineTo(240.0f, 800.0f)
                close()
            }
        }
        .build()
        return _download24px!!
    }

private var _download24px: ImageVector? = null
